definitions:
  api.MapResponse:
    additionalProperties:
      type: string
    type: object
  api.TokenResponse:
    properties:
      expires_at:
        type: string
      token:
        type: string
    type: object
  api.TokenValidationResponse:
    properties:
      expires_at:
        type: string
      token_name:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /healthz:
    get:
      consumes:
      - application/json
      description: used by Kubernetes liveness probe
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Liveness check
      tags:
      - Kubernetes
  /metrics:
    get:
      description: returns HTTP requests duration and Go runtime metrics
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Prometheus metrics
      tags:
      - Kubernetes
  /readyz:
    get:
      consumes:
      - application/json
      description: used by Kubernetes readiness probe
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Readiness check
      tags:
      - Kubernetes
  /readyz/disable:
    post:
      consumes:
      - application/json
      description: signals the Kubernetes LB to stop sending requests to this instance
      produces:
      - application/json
      responses:
        "202":
          description: OK
          schema:
            type: string
      summary: Disable ready state
      tags:
      - Kubernetes
  /readyz/enable:
    post:
      consumes:
      - application/json
      description: signals the Kubernetes LB that this instance is ready to receive
        traffic
      produces:
      - application/json
      responses:
        "202":
          description: OK
          schema:
            type: string
      summary: Enable ready state
      tags:
      - Kubernetes
  /token:
    post:
      consumes:
      - application/json
      description: issues a JWT token valid for one minute
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.TokenResponse'
      summary: Generate JWT token
      tags:
      - HTTP API
  /token/validate:
    post:
      consumes:
      - application/json
      description: validates the JWT token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.TokenValidationResponse'
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Validate JWT token
      tags:
      - HTTP API
  /version:
    get:
      description: returns skeleton version and git commit hash
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.MapResponse'
      summary: Version
      tags:
      - HTTP API
swagger: "2.0"
